### ISSUE TITLE
On Windows the "Number of threads" setting doesn't seem to work correctly

### ISSUE THREAD

**Issue by flozz** [flozz/yoga-image-optimizer#13]
On Windows 1.1.0 doesn't seem to use that Setting correctly the whole time

Eg. For each file a thread is created on "Optimize" start, not when it actually processes the actual file. Making the machine behave oddly under the load, since if you have 1000 files to optimize it will create 1000 threads each using memory and resources, and each using 100% of one core for setting up. The system will starve at one point making even input erroneous (trying to write letters will input `ljk!@@21';s/.//`, so the letters and random punctuation signs). After the threads are created THEN it will start to use only X CPU threads as setup, if the machine still works that is :(

/LE: reworded for clarity

_Originally posted by @licaon-kter in https://github.com/flozz/yoga-image-optimizer/issues/11#issuecomment-922821354_

**Comment by flozz** [comment]
I will try to reproduce this as soon as I can, thank you for the report :)

**Comment by licaon-kter** [comment]
Windows 10 21H1

Also, now I see that the threads are not killed after processing is done, but only on app close.

**Comment by flozz** [comment]
Ok, I was able to reproduce on my Windows VM:

![Capture d’écran de 2021-09-27 12-49-49](https://user-images.githubusercontent.com/971438/134894824-4e782ddb-ad69-4555-a6bd-5af7647912b2.png)

I do not saw the problem before because I often tested with only one image on Windows to check that the optimization works...

I will first try to build a Linux version using [Nuitka](https://nuitka.net/) to see if I can also reproduce it here. I need to know if the problem is caused by Windows, by Nuitka or by a combination of both Windows + Nuitka

**Comment by flozz** [comment]
I was able to reproduce on Linux:

![Capture d’écran de 2021-09-27 13-37-56](https://user-images.githubusercontent.com/971438/134909706-b07a15eb-9663-4c04-b495-c5f523bf580d.png)

But the main difference is that the spawn of the processes consume no CPU so there is no "OS freeze".

Anyway, nice catch, I will work on that this week :+1:

**Comment by flozz** [comment]
I found why there were so much processes. The created process are:

* The main process
* Optimization processes (× "Number of thread" setting), cleaned after optimization
* Manager processes (× number of images), never cleaned

I was misusing the `multiprocessing.Manager()` so one process is created to monitor a task and nothing was cleaned at the end.

I am fixing this so we will have:

* The main process
* Optimization process (× "Number of thread" setting), cleaned after optimization
* 1 manager process, cleaned after optimization

I still do not know why it is so heavy to create processes on Windows but it should reduce the issues. I am building a test version to check it works on my VM :)

**Comment by flozz** [comment]
Ok it seems to work fine for me. If you want to try, the build is available here:

* https://tmp.fgsp.org/.97734209-4d30-442a-aaf1-a4f874812401/yoga-image-optimizer_1.1.0-issue13_win64.zip

I still have a CPU peak at process creation but it is way better than before.

**Comment by flozz** [comment]
Fixed in https://github.com/flozz/yoga-image-optimizer/commit/8fe70b6809b1b7d707d8d0d9e491fdf1ce11ddc0

It will be released soon. Thnak you again for the report! :)
