### ISSUE TITLE
Remove image metadata

### ISSUE THREAD

**Issue by parisni** [flozz/yoga-image-optimizer#16]
Can yoga remove exif metadata during file conversion ?

**Comment by flozz** [comment]
Hello,

Yes, YOGA **always** remove all metadata during conversion / optimization.

:)

**Comment by parisni** [comment]
That's cool and should be emphased in the documentation

thanks

**Comment by flozz** [comment]
You are right, I will add this in the YOGA doc... And on the YOGA Image Optimizer site once I finished it... :)
