### ISSUE TITLE
UI too wide to be usable on most screens

### ISSUE THREAD

**Issue by nekohayo** [flozz/yoga-image-optimizer#17]
Running the Flathub flatpak version.

I rarely have simple and short filenames. The UI is _extremely_ wide because of this, and requires resizing the window's width to somewhat unreasonable sizes in order to be able to see all columns, namely the "Output size" to see how efficient the result was.

I mean, it barely fits on my 2560px-wide screen, and yet I typically do not want a small utility app's window to take more than half of my screen width, it's supposed to be a companion app rather than a centerpiece.

I'm not sure how to solve this elegantly, but here are some ideas.

* I'm not sure the "output image" column is useful at all. But if it is, consider putting that text on a 2nd line below the "input image" text string, separated by a line break character, and using some 50% opacity for the 2nd line or something...
* The Input size and Output size columns should be grouped next to each other, I think those are the most important pieces of information. So move the "Output size" column to be right after "Input size", or put its information on a 2nd line using a linebreak?

**Comment by flozz** [comment]
Yes you are right, the UI is quite basic currently, I have to improve it. I am not sure when I will work on it, but it is on my TODO list for a future version :)

**Comment by flozz** [comment]
Here is a mockup of what it could look like. I do not know yet how to do this with GTK, and I have other subjects to work on before this one. :)

![Capture d’écran de 2021-12-02 13-51-18](https://user-images.githubusercontent.com/971438/144425637-991a2d4d-a1b0-4f8c-be6c-45d2647e07c7.png)

**Comment by nekohayo** [comment]
My guess is that this would be a GtkListBox widget, but have no idea how that works implementation-wise ;)

**Comment by flozz** [comment]
I started working on this issue. Here is a work in progress screenshot :)

![image](https://user-images.githubusercontent.com/971438/190905664-b92f0e1c-4c2b-4f3c-90bc-de1f15cb7537.png)

**Comment by flozz** [comment]
Final version of the compacted interface:

![image](https://user-images.githubusercontent.com/971438/191731016-d47759bb-2252-4d8c-aea2-7a43d2923bb9.png)

This will be released in the next version :)
