### ISSUE TITLE
Affiche toujours "en cours..." après avoir cliqué sur arrêter

### ISSUE THREAD

**Issue by antares35** [flozz/yoga-image-optimizer#2]
Quand on arrête le processus d'optimization avant la fin.
Le statut "Etat" indique toujours "en cours"

![image](https://user-images.githubusercontent.com/43849485/120436799-addae980-c37f-11eb-8c59-9b695a89c56c.png)

**Comment by flozz** [comment]
This is now fixed / c'est maintenant corrigé :)

![Capture d’écran de 2021-07-08 13-07-31](https://user-images.githubusercontent.com/971438/124911844-8534b800-dfed-11eb-8737-d89eb20fdf36.png)
