### ISSUE TITLE
/data/images folder missing after install with PyPi

### ISSUE THREAD

**Issue by lapineige** [flozz/yoga-image-optimizer#4]
#### What happened

I installed YOGA using PyPi, but I can't launch it: `gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/local/lib/python3.8/dist-packages/yoga_image_optimizer/data/images/icon_64.png”: No such file or directory (4)`
It appears that `/usr/local/lib/python3.8/dist-packages/yoga_image_optimizer/data/images/` folder does not exist.

#### What was expected

It works out of the box

#### Step to reproduce

* [x] The bug is always reproducible

Steps to reproduce:

Install via PyPi, following readme instruction.

### System information

* Operating system (with version): Ubuntu 20.10
* How did you installed the software?
    * [x] From PyPI (`pip3 install yoga-image-optimizer`)

**Comment by lapineige** [comment]
Workaround : copy that `images` folder from source code (github archive) to `/usr/local/lib/python3.8/dist-packages/yoga_image_optimizer/data/`

**Comment by flozz** [comment]
The data were probably ignored while building the wheel package... I will fix that tomorrow :)

**Comment by flozz** [comment]
It is now fixed with the **v1.0.1** package on PyPI. I added the translations that were also missing :)
