### ISSUE TITLE
Very slow optimization

### ISSUE THREAD

**Issue by Cwpute** [flozz/yoga-image-optimizer#55]
### Problem description

Optimizing JPEG images takes a huge amount of time (i'm currently trying to process 5 pictures, 2 of which have been done in approximately half an hour). I was wondering it it may be because of my computer being old, or because of a inherently slow process that could,be related to #15 .

### System information

* Operating system (with version):
```
System:
  Kernel: 5.15.0-122-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Xfce 4.18.1
    tk: Gtk 3.24.33 info: xfce4-panel wm: xfwm 4.18.0 vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: LENOVO product: 20AMS7X300 v: ThinkPad X240 serial: <superuser required>
    Chassis: type: 10 serial: <superuser required>
  Mobo: LENOVO model: 20AMS7X300 v: SDK0E50510 WIN serial: <superuser required>
    UEFI-[Legacy]: LENOVO v: GIET76WW (2.26 ) date: 08/27/2014
CPU:
  Info: dual core model: Intel Core i3-4030U bits: 64 type: MT MCP smt: enabled arch: Haswell
    rev: 1 cache: L1: 128 KiB L2: 512 KiB L3: 3 MiB
```

* How did you installed the software?
    * [ ] From PyPI (`pip3 install yoga-image-optimizer`)
    * [ ] From source
    * [ ] Windows Installer
    * [ ] Windows Zip
    * [X] Other: from Flathub at https://flathub.org/apps/org.flozz.yoga-image-optimizer

* YOGA Image Optimizer version: 1.2.4

**Comment by flozz** [comment]
Hello,

You are right, JPEG optimization is very slow. Guetzli, the lib we use to optimize JPEG is very computing heavy (about 3 min and 300 MB of RAM for 1 Mpix photo).

I have to implement other choices for JPEG encoding (MozJPEG alone instead of Guetzli+MozJPEG, and maybe a JPEGli option too) but I have no time to work on it right now ^^'

**Comment by Cwpute** [comment]
It seems it's a problem on my side. The two first pictures did get optimized but the three other encountered an error: 
![image](https://github.com/user-attachments/assets/8e155871-c50d-4bbc-91ef-b252ae754793)

**Comment by Cwpute** [comment]
Ok, good to know. I'll close this issue since it is not an unexpected behavior.

Two suggestions though:
1. Provide some kind of error message that gives the user an idea of why the process ended with an error.
2. Update the description of your app so that it reflects the choices you made regarding optimization: it is slow and heavy, but also extremely efficient.
